version: '2'
services:
  container:
    image: opentosca/container-arm
    ports:
      - '1337:1337'
      - '8081-8087:8081-8087'
    environment:
      - PUBLIC_HOSTNAME=container
      - ENGINE_IA_HOSTNAME=engine-ia
      - ENGINE_IA_PORT=8080
      - ENGINE_PLAN_HOSTNAME=engine-plan
      - ENGINE_PLAN=ODE
      - ENGINE_PLAN_ROOT_URL=http://engine-plan:9763/ode
      - ENGINE_PLAN_SERVICES_URL=http://engine-plan:9763/ode/processes
      - CONTAINER_REPOSITORY_HOSTNAME=container-repository
      - CONTAINER_DEPLOYMENT_TESTS=false
      - CONTAINER_JAVA_OPTS=
    # volumes:
    #   - <path on host system>:/tmp/opentosca
    networks:
      - opentosca
  container-repository:
    image: opentosca/winery-arm
    # volumes:
    #   - <path on host system>:/var/opentosca/repository
    networks:
      - opentosca
  ui:
    image: opentosca/ui-arm
    ports:
      - '8088:8080'
    networks:
      - opentosca
  engine-plan:
    image: opentosca/ode-arm
    ports:
      - '9763:9763' # http
    environment:
      - ENGINE_PLAN_HOSTNAME=engine-plan
      - ENGINE_PLAN_PORT=9763
    networks:
      - opentosca
  engine-ia:
    image: opentosca/engine-ia-arm
    ports:
      - '8090:8080'
      - '1883:1883' # MQTT
    # volumes:
    #   - <path on host system>:/usr/local/tomcat/webapps
    networks:
      - opentosca
  winery:
    image: opentosca/winery-arm
    ports:
      - '8080:8080'
    # volumes:
    #   - <path on host system>:/var/opentosca/repository
    networks:
      - opentosca
networks:
  opentosca:
    driver: bridge
