version: '2'
services:
  container:
    build:
      context: ./container
      args:
        - GIT_BRANCH=master
    ports:
      - '1337:1337'
    networks:
      - opentosca
  engine-ia:
    build: ./engine-ia
    ports:
      - '8080:8080'
    networks:
      - opentosca
  ui:
    build:
      context: ./ui
      args:
        - GIT_BRANCH=master
    ports:
      - '8088:8080'
    networks:
      - opentosca
  engine-plan:
    build: ./engine-plan
    ports:
      - '9443:9443' # https
      - '9763:9763' # http
    networks:
      - opentosca
  container-repository:
    build:
      context: ./winery
      args:
        - GIT_BRANCH=master
    ports:
      - '8081:8080'
    networks:
      - opentosca
  winery:
    build:
      context: ./winery
      args:
        - GIT_BRANCH=master
    ports:
      - '8090:8080'
    networks:
      - opentosca
networks:
  opentosca:
    driver: bridge