version: 2
jobs:
  build_engine_ia:
    machine: true
    steps:
      - checkout
            
      # prepare qemu to emulate an arm device on circle ci
      - run: docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - run: mkdir ./engine-ia/qemu
      - run: cd ./engine-ia/qemu && curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.6.0/qemu-arm-static.tar.gz && tar xzf qemu-arm-static.tar.gz
            
      # build the docker image
      - run: docker build -t wederbn/engine-ia-arm:latest ./engine-ia      
      
      # build the docker image
      - run: > 
          if [ "$CIRCLE_BRANCH" == "master" ]; then
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
            docker push wederbn/engine-ia-arm:latest
          fi
          
  build_bps:
    machine: true
    steps:
      - checkout
            
      # prepare qemu to emulate an arm device on circle ci
      - run: docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - run: mkdir ./bps/qemu
      - run: cd ./bps/qemu && curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.6.0/qemu-arm-static.tar.gz && tar xzf qemu-arm-static.tar.gz
            
      # build the docker image
      - run: docker build -t wederbn/bps-arm:latest ./bps
            
      # push the image
      - run: > 
          if [ "$CIRCLE_BRANCH" == "master" ]; then
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
            docker push wederbn/bps-arm:latest
          fi
          
  build_container:
    machine: true
    steps:
      - checkout
      
      # prebuild the container outside of docker (speeds the build up)
      - run: git clone --recursive --depth=1 https://github.com/OpenTOSCA/container.git -b master ./container/code 
      - run: cd ./container/code && mvn package
            
      # prepare qemu to emulate an arm device on circle ci
      - run: docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - run: mkdir ./container/qemu
      - run: cd ./container/qemu && curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.6.0/qemu-arm-static.tar.gz && tar xzf qemu-arm-static.tar.gz
            
      # build the docker image
      - run: docker build -t wederbn/container-arm:latest ./container
            
      # push the image
      - run: > 
          if [ "$CIRCLE_BRANCH" == "master" ]; then
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
            docker push wederbn/container-arm:latest
          fi
          
  build_ui:
    machine: true
    steps:
      - checkout
      
      # prebuild the ui outside of docker (speeds the build up)
      - run: git clone --recursive --depth=1 https://github.com/OpenTOSCA/ui.git -b master ./ui/code 
      - run: cd ./ui/code && mvn package
            
      # prepare qemu to emulate an arm device on circle ci
      - run: docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - run: mkdir ./ui/qemu
      - run: cd ./ui/qemu && curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.6.0/qemu-arm-static.tar.gz && tar xzf qemu-arm-static.tar.gz
            
      # build the docker image
      - run: docker build -t wederbn/ui-arm:latest ./ui
            
      # push the image
      - run: > 
          if [ "$CIRCLE_BRANCH" == "master" ]; then
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
            docker push wederbn/ui-arm:latest
          fi
          
  build_winery:
    machine: true
    steps:
      - checkout
      
      # prebuild the container client outside of docker (speeds the build up)
      - run: git clone --recursive --depth=1 https://github.com/OpenTOSCA/winery.git -b master ./winery/code 
      - run: cd ./winery/code && mvn package -DskipTests
            
      # prepare qemu to emulate an arm device on circle ci
      - run: docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - run: mkdir ./winery/qemu
      - run: cd ./winery/qemu && curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.6.0/qemu-arm-static.tar.gz && tar xzf qemu-arm-static.tar.gz
            
      # build the docker image
      - run: docker build -t wederbn/winery-arm:latest ./winery
            
      # push the image
      - run: > 
          if [ "$CIRCLE_BRANCH" == "master" ]; then
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
            docker push wederbn/winery-arm:latest
          fi
          
workflows:
  version: 2
  build_all_images:
    jobs:
      - build_engine_ia
      - build_bps
      - build_container
      - build_ui
      - build_winery